name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to master if your default branch is master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # Change to 'build' if your project uses Create React App instead of Vite
          branch: gh-pages
